---
title: "Exercise 2"
output: pdf_document
---
```{r include=FALSE}
require(dplyr)
```
# Exercise 1
a)
```{r}
filter(starwars, name == 'Mace Windu')$homeworld
```
b)
```{r}
count(filter(starwars, species == 'Droid'))
```
c)
```{r}
max_height <- max(filter(starwars, species == 'Human')$height, na.rm = TRUE)
print('Tallest human:')
filter(starwars, species == 'Human', height == max_height)$name
min_height <- min(filter(starwars, species == 'Human')$height, na.rm = TRUE)
print('Shortest human:')
filter(starwars, species == 'Human', height == min_height)$name
```
d)
```{r}
mean(filter(starwars, species == 'Human')$height, na.rm = TRUE)
sd(filter(starwars, species == 'Human')$height, na.rm = TRUE)
```

# Exercise 2
a)
```{r}
Name <- c('Astrid', 'Lea', 'Sarina', 'Remon', 'Letizia', 'Babice', 'Jonas', 'Wendy', 'Niveditha', 'Gioia')
Sex <- c('F', 'F', 'F', 'M', 'F', 'F', 'M', 'F', 'F', 'F')
Age <- c(30, 25, 25, 29, 22, 22, 35, 19, 32, 21)
Superhero <- c('Batman', 'Superman', 'Batman', 'Spiderman', 'Batman', 'Antman', 'Batman', 'Superman', 'Maggott', 'Superman')
Tattoos <- c(11, 15, 12, 5, 65, 3, 9, 13, 900, 0)
pirate_df = data.frame(Name, Sex, Age, Superhero, Tattoos)
pirate_df
```
b)
```{r}
# Mean male age
mean(filter(pirate_df, Sex == 'M')$Age)
# Mean female age
mean(filter(pirate_df, Sex == 'F')$Age)
```
c)
```{r}
pirate_df$tattoos.per.year <- pirate_df$Tattoos / pirate_df$Age
pirate_df
pirate_df[which.max(pirate_df$tattoos.per.year),]$Name
```
d)
```{r}
median(subset(pirate_df, Age > 20 & Superhero == "Spiderman")$Tattoos)
```
e)
```{r}
boxplot(pirate_df$Age, xlab = 'Age')
```
f)
```{r}
data <- table(pirate_df$Superhero)
pie(data, main = 'Pie chart of favourite superhero')
```

# Exercise 3  
a)
```{r}
samples <- rnorm(5, 2, 1/5)
mean(samples)
sd(samples)
```
b)
```{r}
hist(samples, col = 'skyblue3', breaks = seq(1.5, 2.5, length.out = 10))
```
c)
```{r}
mean_5 <- mean(samples)
mean_100 <- mean(rnorm(100, 2, 1/5))
mean_1000 <- mean(rnorm(1000, 2, 1/5))
sd_5 <- sd(samples)
sd_100 <- sd(rnorm(100, 2, 1/5))
sd_1000 <- sd(rnorm(1000, 2, 1/5))
Sample_size <- c(5, 100, 1000)
Mean <- c(mean_5, mean_100, mean_1000)
Sd <- c(sd_5, sd_100, sd_1000)
data <- data.frame(Sample_size, Mean, Sd)
data
```
d)
```{r}
hist(rnorm(100, 2, 1/5), freq = F, ylim = c(0, 2.3),
     main = "100 samples gaussian numbers with mean 2 and sd 1/5",
     xlab = 'Number',
     breaks = seq(1, 3, length.out = 20))
xs <- seq(1.2, 2.8, by = 0.01)
probs <- dnorm(xs, 2, 1/5)
lines(xs, probs, col = 'red')
```
```{r}
hist(rnorm(10000, 2, 1/5), freq = F, ylim = c(0, 2.3),
     main = "10000 samples gaussian numbers with mean 2 and sd 1/5",
     xlab = 'Number',
     breaks = seq(1, 3, length.out = 100))
xs <- seq(1.2, 2.8, by = 0.01)
probs <- dnorm(xs, 2, 1/5)
lines(xs, probs, col = 'red')
```


